services:

  waf:
    image: owasp/modsecurity-crs:nginx
    container_name: waf
    restart: always
    ports:
      - "80:80"                  # Expose port 80 to the outside world
    depends_on:
      - nginx
    volumes:
      - ./modsecurity-crs:/etc/modsecurity.d  # Mount your custom ModSecurity config/rules here if needed
    networks:
      - web_net
      - es_net

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    expose:
      - "8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - nginx_logs:/var/log/nginx
    depends_on:
      - webserver
      - fluentbit
    logging:
      driver: fluentd
      options:
        fluentd-address: host.docker.internal:24224
        tag: docker.nginx
    networks:
      - web_net
      - es_net

  webserver:
    build:
      context: ./webserver
    container_name: webserver
    restart: always
    expose:
      - "8000"
    volumes:
      - ./webserver:/webserver
      - webserver_logs:/var/log/webserver
    env_file:
      - .env
    environment:
      - WATCHFILES_FORCE_POLLING=true
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_started
    networks:
      - postgres_net
      - es_net
      - web_net

  postgres:
    image: postgres:latest
    container_name: webserver-postgres
    restart: always
    shm_size: 128mb
    ports:
      - "${POSTGRESQL_PORT}:${POSTGRESQL_PORT}"
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRESQL_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres_net



  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: es
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - es_net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_started
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kibana/kibana-data-views.ndjson:/usr/share/kibana/kibana-data-views.ndjson:ro
    networks:
      - es_net




  fluentbit:
    image: fluent/fluent-bit:latest
    container_name: fluentbit
    ports:
      - "24224:24224"
    depends_on:
      - elasticsearch
    volumes:
      - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - webserver_logs:/var/log/webserver
    networks:
      - es_net
      - web_net

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - postgres_net

  attack-cli:
    build:
      context: ./attackcli
    container_name: attack-cli
    restart: always
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"


volumes:
  pg_data:
  es_data:
  nginx_logs:
  webserver_logs:

networks:
  postgres_net:
  es_net:
  web_net:
