[project]
name = "http-strike-kit"
version = "0.1.0"
description = "use to attack http servers"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
    "typer>=0.16.0",
]
